### ISSUE TITLE
privateDB.saveRecord is not a function. (In 'privateDB.saveRecord(record,options)', 'privateDB.saveRecord' is undefined)

### ISSUE THREAD

**Issue by Perpetual-Altruism** [1998code/Apple-CloudKit-Catalog-V2#2]
![image](https://user-images.githubusercontent.com/77457615/123355068-bacfa080-d519-11eb-9a5d-c4d0512d258d.png)

Error

privateDB.saveRecord is not a function. (In 'privateDB.saveRecord(record,options)', 'privateDB.saveRecord' is undefined)

**Comment by 1998code** [comment]
Issue investigating.

**Comment by YamamotoKeita** [comment]
I had the same error.

Looking at the CloudKit JS reference, there is no function named "saveRecord", but there is a function named "saveRecords". Perhaps the function name has changed?

https://developer.apple.com/documentation/cloudkitjs/cloudkit/database/1628735-saverecords

**Comment by 1998code** [comment]
Hi @Perpetual-Altruism , @YamamotoKeita ,

All fixed.
